# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/python
pool:
  vmImage: "ubuntu-16.04"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
   git config --global user.email "ci@fake.tld"
   git config --global user.name "CI Services"
  displayName: 'Set up git'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r dev-requirements.txt
  displayName: 'Install dev requirements'

- script: pip install -e .
  displayName: 'Install r2d'

# venv conda 
- script: pytest --durations 10 --cov repo2docker -vs tests/unit
  displayName: 'Run pytest'
