dependencies:
- python=3.5.*
- ipywidgets==7.2.1
- jupyterlab==0.34.9
- nbconvert==5.4.0
- pip:
  # conda-forge dropped python 3.5 support so we use the pip package
  # for notebook
  - notebook==5.7.2
  - nteract_on_jupyter==1.9.6
  - jupyterhub==0.9.4
