#!/bin/bash
# chkconfig: 2345 20 80
# description: Europa API

# Source function library.
. /etc/init.d/functions

start() {
    # code to start app comes here 
    # example: daemon program_name &
    daemon python3 /root/europa/wsgi.py &
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
    killproc python3
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac